version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: fundraising
    volumes:
      - ./app:/var/www
    working_dir: /var/www
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.2
    container_name: mysql
    environment:
      MYSQL_DATABASE: dbfundraising
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  node:
    image: node:22-alpine
    container_name: node
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    tty: true
    ports:
      - "5173:5173"

volumes:
  mysqldata:
